- name: Check Oracle DB status
  hosts: target
  become: yes

  vars:
    oracle_user: oracle
    oracle_sid: XE

  tasks:
    - name: Check if listener is running
      shell: ps -ef | grep tns | grep -v grep
      register: listener_status
      ignore_errors: yes

    - name: Check Oracle DB status using sqlplus
      shell: |
        su - {{ oracle_user }} -c '
          export ORACLE_SID={{ oracle_sid }}
          sqlplus -s / as sysdba <<EOF
          select status from v$instance;
          exit;
EOF
        '
      register: db_status
      ignore_errors: yes

    - name: Show listener status
      debug:
        var: listener_status.stdout

    - name: Show DB status
      debug:
        var: db_status.stdout_lines
