---
- name: Check Oracle listener status
  hosts: target   # or your actual host/group name
  become: yes

  tasks:
    - name: Check if listener is running
      shell: ps -ef | grep tns | grep -v grep
      register: listener_status
      ignore_errors: yes
      changed_when: false

    - name: Print listener status message
      debug:
        msg: >
          {% if listener_status.stdout %}
          Listener is up
          {% else %}
          Listener is down
          {% endif %}

